apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-packages-app-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: github-packages-app-pem
    template:
      type: Opaque
  data:
    - secretKey: key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-packages-app/argocd-github-packages.private-key.pem
        metadataPolicy: None
        nullBytePolicy: Ignore
