apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  refreshInterval: 0
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: auth-secret
    template:
      type: Opaque
      data:
        AUTH_SECRET: "{{ "{{" }} .authSecretRaw | b64enc {{ "}}" }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: auth-secret
