apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: app-secrets
    template:
      type: Opaque
      data:
        AUTH_SECRET: "{{ "{{" }} .password | b64enc {{ "}}" }}"
        AUTH_GOOGLE_ID: "{{ "{{" }} .AUTH_GOOGLE_ID {{ "}}" }}"
        AUTH_GOOGLE_SECRET: "{{ "{{" }} .AUTH_GOOGLE_SECRET {{ "}}" }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: auth-secret
    - extract:
        key: group-wishlist-config
