apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-image-pull-secret
spec:
  refreshInterval: 30m0s
  target:
    name: ghcr-image-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"x-access-token","password":"{{ "{{" }} .token {{ "}}" }}","auth":"{{ "{{" }} printf "x-access-token:%s" .token | b64enc {{ "}}" }}"}}}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: github-packages-app
