apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.buildOptions: --enable-helm
  application.instanceLabelKey: argocd.argoproj.io/instance
  url: http://argo
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
      - type: saml
        id: okta
        name: Okta
        config:
          ssoURL: https://dev-02634852.okta.com/app/dev-02634852_argocd_1/exkd8luqztbtbK1Q25d7/sso/saml
          ca: /var/dex/okta/okta.crt
          redirectURI: https://argocd.benkonicek.com/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupsAttr: group
