---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-webhook-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: argocd-webhook-secret
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-webhook-secret/password
        metadataPolicy: None
        nullBytePolicy: Ignore
