apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-repo-creds
spec:
  refreshInterval: 30m0s
  target:
    name: ghcr-repo-creds
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: ghcr.io/bkonicek
        type: helm
        enableOCI: "true"
        username: x-access-token
        password: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: github-packages-app
