apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-repo-creds
spec:
  refreshInterval: 30m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: ghcr-repo-creds
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: ghcr.io/bkonicek
        type: helm
        enableOCI: "true"
        username: x-access-token
        password: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-read-packages/password
        metadataPolicy: None
        nullBytePolicy: Ignore
