traefik:
  providers:
    kubernetesIngressNGINX:
      enabled: true
  service:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
    spec:
      externalTrafficPolicy: Local
  metrics:
    prometheus:
      serviceMonitor:
        enabled: true
  ingressClass:
    name: traefik
