traefik:
  providers:
    kubernetesIngressNginx:
      enabled: true
  service:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
  metrics:
    prometheus:
      serviceMonitor:
        enabled: true
  ingressClass:
    name: traefik
