traefik:
  providers:
    kubernetesIngressNGINX:
      enabled: true
  service:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
    spec:
      externalTrafficPolicy: Local
  metrics:
    prometheus:
      disableAPICheck: true
      serviceMonitor:
        enabled: true
  ingressClass:
    name: traefik
  additionalArguments:
    - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    # - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
    - "--entrypoints.web.http.redirections.entryPoint.priority=10"
