---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password
spec:
  provider:
    onepasswordSDK:
      vault: Homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account-token
          key: token
      cache:
        ttl: 5m
        maxSize: 100