vpa:
  enabled: true

  recommender:
    extraArgs:
      prometheus-address: |
        http://sandbox-oci-prometheus-ope-prometheus.monitoring.svc.cluster.local:9090
      storage: prometheus

controller:
  flags:
    on-by-default: true
    exclude-namespaces: kube-system,kube-public,kube-node-lease
  rbac:
    extraRules:
      - apiGroups:
        - "monitoring.coreos.com"
        resources:
        - "prometheuses"
        - "alertmanagers"
        verbs:
        - "get"
        - "list"
        - "watch"

dashboard:
  flags:
    on-by-default: true
