vpa:
  enabled: true

  rbac:
    create: true
    extraRules:
      vpaTargetReader:
        - apiGroups: ["monitoring.coreos.com"]
          resources: ["prometheuses", "servicemonitors", "podmonitors", "alertmanagers"] # Adjust resources based on your Prometheus Operator setup
          verbs: ["get", "list", "watch"]

  recommender:
    extraArgs:
      prometheus-address: |
        http://sandbox-oci-prometheus-ope-prometheus.monitoring.svc.cluster.local:9090
      storage: prometheus

controller:
  flags:
    on-by-default: true
    exclude-namespaces: kube-system,kube-public,kube-node-lease
  rbac:
    extraRules:
      - apiGroups:
        - "monitoring.coreos.com"
        resources:
        - "prometheuses"
        - "alertmanagers"
        verbs:
        - "get"
        - "list"
        - "watch"

dashboard:
  flags:
    on-by-default: true
  rbac:
    extraRules:
      - apiGroups:
        - "monitoring.coreos.com"
        resources:
        - "prometheuses"
        - "alertmanagers"
        verbs:
        - "get"
        - "list"
        - "watch"

