{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Compute Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "compartment": "ocid1.tenancy.oc1..aaaaaaaagrijaszt6hht7kcyfsjbgax6d4kigppo234qrs2f6ftp5k7nlocq",
     "compartmentName": "benkonicek",
     "groupBy": "select option (optional)",
     "metric": "instance_status",
     "metricNames": [
      "instance_status",
      "maintenance_status"
     ],
     "namespace": "oci_compute_infrastructure_health",
     "queryText": "instance_status[1m].count()",
     "region": "us-ashburn-1",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "compartment": "ocid1.tenancy.oc1..aaaaaaaagrijaszt6hht7kcyfsjbgax6d4kigppo234qrs2f6ftp5k7nlocq",
     "compartmentName": "benkonicek",
     "groupBy": "select option (optional)",
     "metric": "CpuUtilization",
     "metricNames": [
      "CpuUtilization",
      "DiskBytesRead",
      "DiskBytesWritten",
      "DiskIopsRead",
      "DiskIopsWritten",
      "LoadAverage",
      "MemoryAllocationStalls",
      "MemoryUtilization",
      "NetworksBytesIn",
      "NetworksBytesOut"
     ],
     "namespace": "oci_computeagent",
     "queryText": "CpuUtilization[1m].avg()",
     "region": "us-ashburn-1",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "compartment": "ocid1.tenancy.oc1..aaaaaaaagrijaszt6hht7kcyfsjbgax6d4kigppo234qrs2f6ftp5k7nlocq",
     "compartmentName": "benkonicek",
     "groupBy": "select option (optional)",
     "metric": "MemoryUtilization",
     "metricNames": [
      "CpuUtilization",
      "DiskBytesRead",
      "DiskBytesWritten",
      "DiskIopsRead",
      "DiskIopsWritten",
      "LoadAverage",
      "MemoryAllocationStalls",
      "MemoryUtilization",
      "NetworksBytesIn",
      "NetworksBytesOut"
     ],
     "namespace": "oci_computeagent",
     "queryText": "MemoryUtilization[1m].avg()",
     "region": "us-ashburn-1",
     "resourcegroup": "NoResourceGroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}