apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: grafana-admin-test
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: grafana-admin
