pihole:
  nameOverride: pihole
  serviceDns:
    mixedService: true
    type: ClusterIP
    annotations:
      tailscale.com/expose: "true"
  admin:
    existingSecret: pihole-admin
  doh:
    enabled: true
  replicaCount: 1
  podAnnotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
  podDisruptionBudget:
    enabled: false
  extraEnvVars:
    FTLCONF_dns_listeningMode: "all"
  podDnsConfig:
    enabled: false
  probes:
    liveness:
      initialDelaySeconds: 300
    readiness:
      initialDelaySeconds: 300
