cluster-autoscaler:
  cloudProvider: oci

  extraArgs:
    skip-nodes-with-system-pods: false
    max-node-provision-time: 25m0s
    balance-similar-node-groups: true
    balancing-ignore-label_1: displayName
    balancing-ignore-label_2: hostname
    balancing-ignore-label_3: internal_addr
    balancing-ignore-label_4: oci.oraclecloud.com/fault-domain

  image:
    repository: iad.ocir.io/oracle/oci-cluster-autoscaler
    tag: 1.27.2-9 # https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler_topic-Working_with_the_Cluster_Autoscaler.htm#Working_with_the_Cluster_Autoscaler
    imagePullPolicy: Always

  extraEnv:
    OKE_USE_INSTANCE_PRINCIPAL: true
    OCI_SDK_APPEND_USER_AGENT: "oci-oke-cluster-autoscaler"

  replicaCount: 2
