apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/v1.58.0/cmd/k8s-operator/deploy/crds/tailscale.com_connectors.yaml # 1.56.1 (no release with CRDs yet)
  - operator-oauth-sealed-secret.yaml
  - namespace.yaml # prevent migration to Helm chart from deleting namespace defined in previous manifests

helmCharts:
  - name: tailscale-operator
    includeCRDs: false
    releaseName: tailscale-operator
    version: 1.56.1
    repo: https://pkgs.tailscale.com/helmcharts
    valuesInline:
      operatorConfig:
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            memory: 100Mi
