apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - operator-oauth-sealed-secret.yaml
  - namespace.yaml # prevent migration to Helm chart from deleting namespace defined in previous manifests

helmCharts:
  - name: tailscale-operator
    includeCRDs: false
    releaseName: tailscale-operator
    version: 1.58.2
    repo: https://pkgs.tailscale.com/helmcharts
    valuesInline:
      operatorConfig:
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            memory: 100Mi
