tailscale-operator:
  operatorConfig:
    resources:
      requests:
        cpu: 500m
        memory: 100Mi
      limits:
        memory: 100Mi

appConnector:
  enabled: false
  image:
    repository: tailscale/tailscale
    tag: v1.84.3
