external-dns:
  provider: cloudflare
  policy: sync
  managedRecordTypes:
    - A
    - AAAA
    - CNAME
    - TXT
  sources:
    - ingress
    - crd
  txtOwnerId: external-dns
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cf-dns
          key: API_TOKEN

  serviceMonitor:
    enabled: true

# DNS zone
dnsZone: benkonicek.com
