apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ts-app-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-app-connector
  serviceName: ts-app-connector
  template:
    metadata:
      labels:
        app: ts-app-connector
    spec:
      containers:
        - env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_ACCEPT_DNS
              value: "false"
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: operator-oauth
                  key: client_secret
                  optional: false
            - name: TS_EXTRA_ARGS
              value: >
                --advertise-connector
                --advertise-tags=tag:connector
                --snat-subnet-routes
                --reset
            - name: TS_ROUTES
              value: 129.213.200.122/32
          {{- with .Values.appConnector.image }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          name: tailscale
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      serviceAccount: proxies
      serviceAccountName: proxies
