# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus
    namespace: monitoring
    version: v56.6.2
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
