kube-prometheus-stack:
  kubeEtcd:
    enabled: false

  grafana:
    plugins:
      - oci-metrics-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: oci-metrics-datasource
            type: oci-metrics-datasource
            editable: true
            access: proxy
            jsonData:
              profile0: "DEFAULT"
              environment: "OCI Instance"
