kube-prometheus-stack:
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false

  grafana:
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: grafana
    admin:
      existingSecret: "grafana-admin"
      userKey: username
      passwordKey: password
    plugins:
      - oci-metrics-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: oci-metrics-datasource
            type: oci-metrics-datasource
            editable: true
            access: proxy
            jsonData:
              profile0: "DEFAULT"
              environment: "OCI Instance"
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: "externaldns"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/edns
    dashboards:
      default:
        argocd:
          url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json
          token: ""
        ingress-nginx:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/grafana/dashboards/nginx.json
          token: ""
        external-dns:
          gnetId: 15038
          revision: 3
          datasource: Prometheus
    dashboardsConfigMaps:
      edns: sandbox-oci-sealed-secrets-controller-sealed-secrets-controller

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
