apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/oci.oraclecloud.com~1load-balancer-type
        value: "nlb"
    target:
      group: apps
      version: v1
      kind: Service
      labelSelector: "app.kubernetes.io/component: controller"
