kind: Deployment
apiVersion: apps/v1
metadata:
  name: pihole
  annotations:
    operator.1password.io/item-path: "vaults/Homelab/items/pihole-admin-password"
    operator.1password.io/item-name: "pihole-admin"
