apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

helmCharts:
  - name: pihole
    releaseName: pihole
    version: 2.18.0
    repo: https://mojo2600.github.io/pihole-kubernetes/
    valuesFile: values.yaml

secretGenerator:
  - name: pihole-admin
    files:
      - password

generatorOptions:
  disableNameSuffixHash: true
