apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgCTmvyy1RXvU/8wRMQW9eQTxTcQvNH3URUWPnmEFImRs14lCkSxQSJOjYw639VhZ5mOmnOCoWaty9bVmPMISfsZWGP/x4sAgGpvv+hyY/ZsmrBopjCN9FGKAogh9eokLsyPnR+PGZWJfn3AP+CdV4t2c8MsaJiTVhN0oUnyH6j+LM4WAFYsLa76vzwJk+/cX42QEssqPZ95rbHwGMTkFH7avSCCiF+B/A7x3HZY+Jjcrwe6+UP5/QcULu8l6I8OpCCSA7xTZD9RaUnPIlD6MR3Rm8cckjuXd2kzOzPxLny1tXagfGjNKdCqpv5w62faTK6yzbyg94MN4CPdnctyvJ5lvWaDctVi3Y9HajVsQ9KOprzFsCfN1N51D4iTHK8ZH/yvj+2eUqV7krynUOXsIGAX/yEk1/k/TrlACjlICk4of5gg1yJVSdHxxpKB1Riu86sX+sdwLC2atKaBS9ifRPbH2uB6I/yWeAlsjIzZcQRKesB4KqwRc37zbmjZlHUSoiTT2Pr0B5bupJ9/M/TQN+vfpoFouAnQ/WpMukF2TXzlomTxM4JJwzGuX7h1v4O/l1Pw8sfvlB18vmsOOEwm8gvJeDpigGwY9N5kPNlkfa/2ZLjk+LzTOKBwMPKHNyow+qt78ny/lckYzY40yvojM8gTZ6RqTw+QyQ6Srj1wnw6yq2uKr5Ce3Q8u+LpntRa7imBl/Fwq9MVmVWKjdKzrsvc=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: pihole

