apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.alerting.slack.secretName }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: {{ .Values.alerting.slack.secretName }}
    template:
      type: Opaque
      data:
        {{ .Values.alerting.slack.secretKey }}: "{{ `{{ .password }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.alerting.slack.secretStore.secretName }}
