apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ .Values.spec.source.repoURL }}
        revision: {{ .Values.spec.source.targetRevision }}
        directories:
          - path: system/*
  template:
    metadata:
      name: '{{ "{{" }}.path.basename{{ "}}" }}'
    spec:
      project: default
      destination:
        namespace: kube-system
        server: {{ .Values.spec.destination.server }}
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        path: '{{ "{{" }}.path.path{{ "}}" }}'
      syncPolicy: {}
  syncPolicy:
    preserveResourcesOnDeletion: true
