# AppSet for custom apps that don't necessarily follow the pattern of the others.
# Path structure is custom/<namespace>/<app name>
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ .Values.spec.source.repoURL }}
        revision: {{ .Values.spec.source.targetRevision }}
        files:
          - path: environments/*/*/config.yaml
  template:
    metadata:
      name: '{{`{{index .path.segments 1}}`}}'-'{{`{{.path.basenameNormalized}}`}}'
      labels:
        app_name: '{{ .path.basenameNormalized }}'
    spec:
      project: default
      destination:
        namespace: '{{`{{ .namespace }}`}}'
        server: {{ .Values.spec.destination.server }}
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: '{{`{{ .targetRevision }}`}}'
        path: '{{`{{ .path.path }}`}}'
      syncPolicy:
        automated:
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: true # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:
          - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: true
