apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: pihole-admin
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: pihole-admin-password/password
        metadataPolicy: None
        nullBytePolicy: Ignore
