{{- range $name, $value := .Values.dnsEndpoints }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ trimPrefix "_" $name }}
spec:
  endpoints:
  - dnsName: {{ $name }}.{{ $.Values.dnsZone }}
    recordTTL: {{ $value.ttl }}
    recordType: {{ $value.type }}
    targets:{{- if eq $value.type "TXT" }}
{{- range $t := $value.targets }}
      - {{ printf "\"%s\"" $t | quote }}
{{- end }}
    {{- else }} {{ toYaml $value.targets | nindent 6 }}
    {{- end }}
    {{- if $value.proxy }}
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "true"
    {{- end }}
---
{{- end }}
