DNS1: 10.96.5.5
serviceDns:
  mixedService: true
  type: ClusterIP
  annotations:
    tailscale.com/expose: "true"
admin:
  existingSecret: pihole-admin
replicaCount: 2
image:
  repository: pihole/pihole
  tag: "2023.10.0"
