{{- range $name, $value := .Values.dnsEndpoints }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ $name }}
spec:
  endpoints:
  - dnsName: {{ $name }}.{{ $.Values.dnsZone }}
    recordTTL: {{ $value.ttl }}
    recordType: {{ $value.type }}
    targets: {{ toYaml $value.targets | nindent 6 }}
    {{- if $value.proxy }}
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "true"
    {{- end }}
{{- end }}
