apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-issuer-http
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-http-issuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
