apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.crds.yaml
  - clusterissuer-http-staging.yaml
  - clusterissuer-http.yaml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.13.3
    repo: https://charts.jetstack.io
    valuesFile: values.yaml

patches:
  - path: ./remove-instance-label.jsonpatch.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
