namespace: cert-manager
clusterResourceNamespace: cert-manager
global:
  leaderElection:
    namespace: cert-manager
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    labels:
      release: prometheus
