apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: 1password
spec:
  encryptedData:
    token: AgBfoW5sTstoPBRULYEakqFc1dxn7HvMY+o28AgaqT0tDZ+nykwwFK1jaIzxANkh/0XMfYcoYAKz4/ZCjAyML6dpIKo7t5VMXNyz0yfHLZf2K+ME9t7rSKQks9hcQQanOxso7BurXM7QsgqgxZ8iiiE/HXQplW1p0yEY+LCZD3D9cJyypTQOvAb6Gqom3pevsALeSXRSAUMpujosNrs53CIoXBpzuxImMeTKj+jAooYvhlyRCjAZMdjdt9a4knORdFm9TZ7ukak7uSPXy4AkWTKRtYJIQaQ11qw3dexwsFFuiPyoHKpVv7g94EoAqK8IKRiTE5pYS+auS85vla8+CydvCvaypGZUVpBtQrsMoeGW3ppQ1TeMMbYVyu732KJyLk3wCWpiyYIuZ1QhKJjQ4JOF82tkgHWXkL74X/sopd2GjWDEXRpWAy3DE0enX7rcewnPfDHCdH91jCeRhg1NqEzBWNfHY3swn1AcfW7/9f+gTI3PGER75sjTNDqCzHt7mZ01Bb8PoS5+vhYlprs4FMwSXxDAYMEF5Oryv3eS+s0b7rfVA5LiRWRNjz7w6PCqqOaIp0W8g5VwDdf0sUadS+sl6ziD//OeB/Tp86Fbb00VfmNZHrsa+MC7TP9vDCZFbfILFI/8LI/S08QtFXdByvJh7U+ctg7vaHD/317whlibuYcfmO0CI0DVXyYBBZZ11m1mAG2UMy0abF2YzhTBKPgWuyIBDcM67csoJjWBFEQjsry0jrJ4w5HFNmNYB28qk7UnI71WzpwaSdeK1ZwLN4H79xtaifakJB6gZVeJk0DCxGPdiF4of/sCgzdjEaPtJpK20QOdFSOe/kRRgjuMmVrdLMlNeATLlpgMRQ1oVNodO66ohAsRW5H/ElXeMtTqcd8duk2j1GtjCg57+HumZWiSL8YVYUkLETDjRi+sm0qkuJEC2ysNvS2w6em/L1BRJMNNA/GQZeDawfE+1KayT2Dyn8Ktq5uV2PyPohz1TtIGTJZ2SgMMTVYzMfRn/1hJCWB1d/e4bQnZz0JxR5nyReCikwjRJrYQ+54WDCSwRXbcw7dYwrc8MJowp2YWE7sXqgikKcFxGLfrKlI/f+LbosEEMZ6MccVgGuwZOUbLj76pPhqkJstHJZP5h4/6Jgh92l8uhgNgeL3XvFy0H04OjBWPtcRFLo6HChFaJcY8F9DtKtyUc4gyXmV7FXcWregdVCMYJscT+bH17+9mBSAIEynVydmlbY0JN7RzN6E9j+SL10DLC7Iwx78ZLflvUoGL0xWndKdo8FMbBFJfhBoXHYdn55OV870ue1F/a+D2EgvxCS5eKZN1KscTyrxMdesAdm3muYT7/VN3PbN1ioXE2ck8qH4R5qfz0m4ZxrDw2yPEJX5FAh/uElI6Yx1+fQCPffRb0J30aEwJ8dG1d38H4W+hoRgQrlx3ytBV8nFvRMxZsmPH+JWpiHT0gnM+E961CdUxz2PxsuChuPCoXgb9JFjDicyCcbR9sep7egPdZGQJ3Kox/PnT5eVZEQMeusx0USnPQDAKMeu4s6L3NHdJ9zmG3xI=
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: 1password

