apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 1password

helmCharts:
  - name: connect
    includeCRDs: true
    releaseName: 1password-connect-server
    version: 1.15.0
    repo: https://1password.github.io/connect-helm-charts/
    valuesFile: values.yaml

resources:
  - 1password-credentials-sealed-secret.yaml
  - 1password-token-sealed-secret.yaml
