ingress-nginx:
  controller:
    replicaCount: 2
    service:
      externalTrafficPolicy: Local
      annotations:
        oci.oraclecloud.com/load-balancer-type: "nlb"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
