apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

helmCharts:
  - name: external-dns
    includeCRDs: true
    releaseName: external-dns
    version: 1.14.2
    repo: https://kubernetes-sigs.github.io/external-dns/
    valuesFile: values.yaml

resources:
  - cloudflare-sealed-secret.yaml
