external-dns:
  extraArgs:
    - "--exclude-target-net=10.0.0.0/8"
    
# Create DNSEndpoint resources
dnsEndpoints:
  blog:
    type: CNAME
    targets:
      - bkonicek.github.io
    proxy: false
    ttl: 180
