external-dns:
  extraArgs:
    - "--exclude-target-net=10.0.0.0/8"

# Create DNSEndpoint resources
dnsEndpoints:
  blog:
    type: CNAME
    targets:
      - bkonicek.github.io
    proxy: false
    ttl: 180
  _github-pages-challenge-bkonicek:
    type: TXT
    targets:
      - "83f0bb0b77613304179af6b534e2d3"
    proxy: false
    ttl: 180
